# Run: conda env create --file environment.yml
name: dcd_tsp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - anaconda
  - tqdm
  - pytorch=2.1.1
  - pytorch-cuda=11.8
  - torchvision
  - pip
  - pip:
    - tensorboard_logger
